name: MacOS Workflow

on:
  pull_request:
    branches: [ gcos4gnucobol-3.x ]
  push:
    branches: [ gcos4gnucobol-3.x ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          brew install automake help2man texinfo bison berkeley-db@4
          opt="/usr/local/opt"; \
          for d in automake help2man bison texinfo berkeley-db@4; do \
            test -d "$opt/$d/bin" && echo "$opt/$d/bin" >> $GITHUB_PATH; \
            test -d "$opt/$d/lib" && export LDFLAGS="-L$opt/$d/lib $LDFLAGS"; \
            test -d "$opt/$d/include" && export CPPFLAGS="-I$opt/$d/include $CPPFLAGS"; \
          done; \
          echo "LDFLAGS=${LDFLAGS}" >> $GITHUB_ENV; \
          echo "CPPFLAGS=${CPPFLAGS}" >> $GITHUB_ENV

      - name: Set git user
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions-bot@users.noreply.github.com

      - name: bootstrap
        run: |
          ./autogen.sh

      - name: Build environment setup
        run: |
          mkdir _build
          echo "NPROC=`sysctl -n hw.ncpu`" >> $GITHUB_ENV

      - name: configure
        run: |
          cd _build
          ../configure --enable-cobc-internal-checks --enable-debug --prefix /opt/cobol/gnucobol-gcos --exec-prefix /opt/cobol/gnucobol-gcos

      - name: make
        run: |
          cd _build
          make --jobs=$((${NPROC}+1))

      - name: check
        run: |
          cd _build
          make check TESTSUITEFLAGS="--jobs=$((${NPROC}+1))"

      - name: install
        run: |
          cd _build
          sudo make install
